# Jupyterlab with Geo packages (March 2024)
# FROM yufernando/jupyterlab:lab-4.1.5 --> not compatible with vim
FROM yufernando/jupyterlab:lab-4.0.9

LABEL maintainer="Fernando Yu <yufernando@gmail.com>"

# USER INSTALL
USER ${NB_UID}
ENV HOME "/home/${NB_USER}"

# INSTALL PYTHON PACKAGES
RUN mamba install --quiet --yes         \
    -c conda-forge                      \
    geopandas                           \
    shapely                             \
    fiona                               \
    momepy                              \
    osmnx                               \
    geopy                               \
    pytest;                             \
    mamba install --quiet --yes         \
    -c mullenkamp osm2geojson;          \
    conda clean --all -f -y

WORKDIR "${HOME}/work"
