# Jupyterlab with Geo packages (March 2024)
# FROM yufernando/jupyterlab:lab-4.1.5 --> not compatible with vim
#
#########################################
# NOTE (June 2024): This Dockerfile does not work. Fiona (below) throws an installation
# error
#########################################

FROM yufernando/jupyterlab:lab-4.0.9

LABEL maintainer="Fernando Yu <yufernando@gmail.com>"

USER root
RUN apt install -y gdal-bin libgdal-dev g++

# USER INSTALL
USER ${NB_UID}
ENV HOME "/home/${NB_USER}"

# This gives me an installation error
RUN mamba install --quiet --yes         \
    fiona

WORKDIR "${HOME}/work"
