version: '3'
services:
  lab:
    container_name: jupyterlab
    image: yufernando/jupyterlab
    volumes:
      - ./notebooks:/home/jovyan/work
    working_dir: /home/jovyan/work/
    ports:
      - '8888:8888'
    restart: always
    environment:
      JUPYTER_ENABLE_LAB: 'yes'

  c-lang:
    container_name: c-lang
    image: yufernando/c-lang
    volumes:
      - .:/root/work
    working_dir: /root/work
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: /bin/zsh
